export const DT = 1/60;
export const TOUCH_FORCE_RADIUS = 30;
export const TOUCH_COLOR_RADIUS = 30;
export const PRESSURE_CALC_ALPHA = -1;
export const PRESSURE_CALC_BETA = 0.25;
export const VELOCITY_DIFFUSION_ALPHA = 1/DT;
export const VELOCITY_DIFFUSION_BETA = 1/(4 + VELOCITY_DIFFUSION_ALPHA);
export const NUM_PARTICLES = 131072;
export const PARTICLE_LIFETIME = 1000;