export const DT = 1 / 60;
export const TOUCH_FORCE_RADIUS = 30 / 1280; // Give the radius as a fraction of the largest dim of the canvas.
export const TOUCH_FORCE_SCALE = 0.3;
export const MIN_TOUCH_FORCE_RADIUS_PX = 15;
export const MAX_TOUCH_FORCE_RADIUS_PX = 50;
export const PRESSURE_CALC_ALPHA = -1;
export const PRESSURE_CALC_BETA = 0.25;
export const PARTICLE_DENSITY = 0.1;// Approx avg num particles per px.
export const MAX_NUM_PARTICLES = 130000;
export const PARTICLE_LIFETIME = 1000;
export const TRAIL_LIFETIME = 100;
export const NUM_RENDER_STEPS = 3;